# Generated by Django 2.2 on 2019-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(to='core.Transaction'),
        ),
    ]
