# Generated by Django 2.2 on 2019-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
