# Generated by Django 2.2 on 2019-05-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_commission_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconversionrate',
            old_name='rate',
            new_name='conversion_rate',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='commission',
            new_name='commission_rate',
        ),
    ]
